name: bert
channels:
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - ca-certificates
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libstdcxx-ng
  - ncurses
  - openssl
  - pip
  - python
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
      - aiohttp
      - aiosignal
      - async-timeout
      - attrs
      - certifi
      - charset-normalizer
      - cmake
      - comet-ml
      - configobj
      - dulwich
      - everett
      - filelock
      - frozenlist
      - fsspec
      - huggingface-hub
      - idna
      - jinja2
      - jsonschema
      - jsonschema-specifications
      - lightning-utilities
      - multidict
      - numpy
      - packaging
      - pillow
      - psutil
      - pygments
      - python-box
      - python-dotenv
      - pytorch-lightning
      - pyyaml
      - referencing
      - regex
      - requests
      - requests-toolbelt
      - rich
      - rpds-py
      - safetensors
      - semantic-version
      - sentry-sdk
      - simplejson
      - six
      - sympy
      - tokenizers
      - torch
      - torchmetrics
      - torchvision
      - tqdm
      - transformers
      - triton
      - typing-extensions
      - urllib3
      - websocket-client
      - wrapt
      - wurlitzer
      - yarl
      - wandb
